

#Apply via: ansible-playbook -i ./inventory.yaml --become stack_base_config.yaml

#---------------------------------------------------------------

- name: General OS Config 
  hosts: stack
  tasks:
    - name: Set Timezone
      command: timedatectl set-timezone Europe/Berlin

    - name: update apt repo package lists
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Create hosts file from J2 Template
      template:
        src: ./config_templates/hosts.template
        dest: /etc/hosts
  
#---------------------------------------------------------------